#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Please visit https://marketplace.digitalocean.com/apps/jitsi
for instructions on how to use and administer this droplet.

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
